In [1]:
import pandas as pd 
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df_train = pd.read_csv(r'C:\Users\Ben Wong\Desktop\Venturenix Lab\Data Collection\Titanic\train.csv')
df_test = pd.read_csv(r'C:\Users\Ben Wong\Desktop\Venturenix Lab\Data Collection\Titanic\test.csv')

In [4]:
#df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
usecols = ['Pclass','Sex','Age','SibSp','Parch','Embarked']

X = df_test[usecols]
#y = df_train['Survived']

In [5]:
DEFAULT_AGE = df_train['Age'].mean()
X['Age'] = X['Age'].fillna(DEFAULT_AGE)

<ipython-input-5-e484f1d8b118>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Age'] = X['Age'].fillna(DEFAULT_AGE)


In [6]:
X

Pclass     Sex        Age  SibSp  Parch Embarked
0         3    male  34.500000      0      0        Q
1         3  female  47.000000      1      0        S
2         2    male  62.000000      0      0        Q
3         3    male  27.000000      0      0        S
4         3  female  22.000000      1      1        S
..      ...     ...        ...    ...    ...      ...
413       3    male  29.699118      0      0        S
414       1  female  39.000000      0      0        C
415       3    male  38.500000      0      0        S
416       3    male  29.699118      0      0        S
417       3    male  29.699118      1      1        C

[418 rows x 6 columns]

In [10]:
#DEFAULT_CABIN_CODE = 'X'
#X['Cabin_code'] = X['Cabin'].fillna(DEFAULT_CABIN_CODE).apply(lambda x:x[0])

<ipython-input-10-9caab0814b14>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Cabin_code'] = X['Cabin'].fillna(DEFAULT_CABIN_CODE).apply(lambda x:x[0])


In [7]:
DEFAULT_EMBARKED = 'S'
X['Embarked'] = X['Embarked'].fillna(DEFAULT_EMBARKED)

<ipython-input-7-17a5efac1e84>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Embarked'] = X['Embarked'].fillna(DEFAULT_EMBARKED)


In [8]:
onehot_cols = ['Sex','Embarked']
num_cols = ['Pclass','Age','SibSp','Parch',]
X_getdummies = pd.get_dummies(X[onehot_cols],drop_first = True)

In [9]:
X_getdummies.head()

Sex_male  Embarked_Q  Embarked_S
0         1           1           0
1         0           0           1
2         1           1           0
3         1           0           1
4         0           0           1

In [10]:
X_training = pd.concat([X, X_getdummies],axis=1)

In [11]:
X_training.head()

Pclass     Sex   Age  SibSp  Parch Embarked  Sex_male  Embarked_Q  \
0       3    male  34.5      0      0        Q         1           1   
1       3  female  47.0      1      0        S         0           0   
2       2    male  62.0      0      0        Q         1           1   
3       3    male  27.0      0      0        S         1           0   
4       3  female  22.0      1      1        S         0           0   

   Embarked_S  
0           0  
1           1  
2           0  
3           1  
4           1

In [12]:
X_training.drop(['Sex','Embarked'],axis=1,inplace=True)

In [13]:
X_training

Pclass        Age  SibSp  Parch  Sex_male  Embarked_Q  Embarked_S
0         3  34.500000      0      0         1           1           0
1         3  47.000000      1      0         0           0           1
2         2  62.000000      0      0         1           1           0
3         3  27.000000      0      0         1           0           1
4         3  22.000000      1      1         0           0           1
..      ...        ...    ...    ...       ...         ...         ...
413       3  29.699118      0      0         1           0           1
414       1  39.000000      0      0         0           0           0
415       3  38.500000      0      0         1           0           1
416       3  29.699118      0      0         1           0           1
417       3  29.699118      1      1         1           0           0

[418 rows x 7 columns]

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
scaler.fit(X_training)
X_norm = scaler.transform(X_training)

In [16]:
X_norm

array([[ 0.87348191,  0.34428417, -0.49947002, ...,  0.75592895,
         2.84375747, -1.35067551],
       [ 0.87348191,  1.33465451,  0.61699237, ..., -1.32287566,
        -0.35164743,  0.74037028],
       [-0.31581919,  2.52309891, -0.49947002, ...,  0.75592895,
         2.84375747, -1.35067551],
       ...,
       [ 0.87348191,  0.66120268, -0.49947002, ...,  0.75592895,
        -0.35164743,  0.74037028],
       [ 0.87348191, -0.03608795, -0.49947002, ...,  0.75592895,
        -0.35164743,  0.74037028],
       [ 0.87348191, -0.03608795,  0.61699237, ...,  0.75592895,
        -0.35164743, -1.35067551]])

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.33, random_state=42)

In [72]:
# Define model
lr = LogisticRegression()

In [73]:
# Train model
lr.fit(X_train,y_train)

LogisticRegression()

In [74]:
# Prediction
df_result = pd.DataFrame(y_train)
df_result['predicted'] = lr.predict(X_train)

In [76]:
df_result

Survived  predicted
6           0          0
718         0          0
685         0          0
73          0          0
882         0          1
..        ...        ...
106         1          1
270         0          0
860         0          0
435         1          1
102         0          0

[596 rows x 2 columns]

In [82]:
from sklearn.metrics import confusion_matrix, classification_report

In [93]:
y_actaul = df_result['Survived']
y_predicted = df_result['predicted']

In [94]:
confusion_matrix(y_actaul,y_predicted)

array([[322,  52],
       [ 70, 152]], dtype=int64)

In [96]:
print(classification_report(y_actaul,y_predicted))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       374
           1       0.75      0.68      0.71       222

    accuracy                           0.80       596
   macro avg       0.78      0.77      0.78       596
weighted avg       0.79      0.80      0.79       596



In [86]:
from sklearn.svm import SVC

In [87]:
svm = SVC()

In [88]:
svm.fit(X_train,y_train)

SVC()

In [97]:
# Prediction
df_result2 = pd.DataFrame(y_train)
df_result2['predicted'] = svm.predict(X_train)

In [98]:
df_result2

Survived  predicted
6           0          0
718         0          0
685         0          0
73          0          0
882         0          0
..        ...        ...
106         1          0
270         0          0
860         0          0
435         1          1
102         0          0

[596 rows x 2 columns]

In [99]:
confusion_matrix(df_result2['Survived'], df_result2['predicted'])

array([[359,  15],
       [ 77, 145]], dtype=int64)

In [100]:
print(classification_report(df_result2['Survived'], df_result2['predicted']))

              precision    recall  f1-score   support

           0       0.82      0.96      0.89       374
           1       0.91      0.65      0.76       222

    accuracy                           0.85       596
   macro avg       0.86      0.81      0.82       596
weighted avg       0.85      0.85      0.84       596

